{{- if .Values.ingress.create -}}
{{- $root := . }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-fastapi-2-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http: 
      paths:
      {{- range .Values.ingress.paths }}
        - path: {{ .path }}
          pathType: {{ .pathType }}
          backend:
            service:
              name: auth-server-service
              port:
                number: {{ $root.Values.auth_server.service_port }}
      {{- end }}

{{- end }}