apiVersion: v1
kind: Secret
metadata:
  name: auth-fastapi-2-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
data: 
  PRIVATE_KEY: {{ .Values.auth_server.PRIVATE_KEY_base64 }}
  SECRET_KEY: {{ .Values.auth_server.SECRET_KEY_base64 }}

  {{- $rabbitmq_user := .Values.broker.user_base64 | b64dec }}
  {{- $rabbitmq_password := .Values.broker.password_base64 | b64dec  }}
  {{- $database_user := .Values.database.user_base64 | b64dec  }}
  {{- $database_password := .Values.database.password_base64 | b64dec  }}
  
  RABBITMQ_URI: {{ printf "amqp://%s:%s@%s/%s" $rabbitmq_user $rabbitmq_password .Values.broker.hostname .Values.broker.vhost_name | b64enc }}
  DATABASE_URI: {{ printf "%s:%s@%s/%s" $database_user $database_password .Values.database.hostname .Values.database.database | b64enc }}
  SENDER_EMAIL: {{ .Values.email_worker.SENDER_EMAIL_base64 }}
  SENDER_EMAIL_PASSWORD: {{ .Values.email_worker.SENDER_EMAIL_PASSWORD_base64 }}

{{- if .Values.is_test }}
  RABBITMQ_USER: {{ .Values.broker.user_base64 }}
  RABBITMQ_PASS: {{ .Values.broker.password_base64 }}
  DATABASE_USER: {{ .Values.database.user_base64 }}
  DATABASE_PASS: {{ .Values.database.password_base64 }}
{{- end }}
