apiVersion: v1
kind: Service
metadata:
  name: auth-server-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: auth-server
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.auth_server.service_port }}
    targetPort: 80

{{- if .Values.is_test }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.broker.hostname }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: broker
  ports:
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.hostname }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: database
  ports:
  - name: sql
    protocol: TCP
    port: 5432
    targetPort: 5432
{{- end }}