apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-{{ .Values.name_suffix }}
type: Opaque
data:
  root_user: {{ .Values.root_user | b64enc }}
  root_user_pwd: {{ .Values.root_user_pwd | b64enc }}
  aws_access_key_id: {{ .Values.backups.aws_access_key_id_base64 }}
  aws_secret_access_key: {{ .Values.backups.aws_secret_access_key_base64 }}

  {{- if .Values.pgadmin.enable }}
  #_________________PGADMIN_CONF___________________________________________#
  pgadmin_user: {{ .Values.pgadmin.admin_email | b64enc }}
  pgadmin_pwd: {{ .Values.pgadmin.admin_pwd | b64enc }}

  servers.json: |
    {{- include (print $.Template.BasePath "/_servers.json.txt") . | b64enc | nindent 4 }}
  
  pgpass: |
    {{- include (print $.Template.BasePath "/_pgpass.txt") . | b64enc | nindent 4 }}
  {{- end }}
  

  {{- if .Values.metrics.enable }}
  #_______________EXPORTER_CONF______________________________________#
  exporter_source: {{ printf "postgresql://%s:%s@localhost:5432/postgres?sslmode=disable" .Values.root_user .Values.root_user_pwd | b64enc }}
  {{- end }}


  {{- if .Values.cluster_mode.enable }}
  #_________________SOME_CLUSTER_CONF___________________________________________#
  cluster_key: |
    {{- .Values.cluster_mode.cluster_key | b64enc | nindent 4}}
  
  #_____________________________PG_POOL_CONF_________________________________________#
  pool_passwd: |
    {{- include (print $.Template.BasePath "/_pool_passwd.txt") . | b64enc | nindent 4 }}
  
  pgpool.conf: |
    {{- include (print $.Template.BasePath "/_pgpool.conf.txt") . | b64enc | nindent 4 }}
    
  pool_hba.conf: |
    {{- include (print $.Template.BasePath "/_pool_hba.conf.txt") . | b64enc | nindent 4 }}
  
  {{- end }}

  #__________________________CONFIG_JOB_ENTRYPOINT____________________________________#
  config_job_entrypoint.sh: |
    {{- include (print $.Template.BasePath "/_cluster-config.sh.txt") . | b64enc | nindent 4 }}
