{{- if .Values.cluster_mode.enable }}
#_________________________READ_REPLICAS_STATEFULSET________________________#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}-{{ .Values.name_suffix }}-read
  labels:
    app: {{ .Values.name }}-{{ .Values.name_suffix }}
    type: read
spec:
  replicas: {{ .Values.cluster_mode.readReplicas }}
  serviceName: "{{ .Values.name }}-{{ .Values.name_suffix }}-read"
  selector:
    matchLabels:
      app: {{ .Values.name }}-{{ .Values.name_suffix }}
      type: read
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-{{ .Values.name_suffix }}
        type: read
      annotations:
        {{- $config_map := include (print $.Template.BasePath "/configmap.yaml") . }}
        {{- $secret := printf "%s%s%s" .Values.root_user .Values.root_user_pwd .Values.cluster_mode.cluster_key }}
        checksum/config: {{ printf "%s%s" $config_map $secret | sha256sum }}
    spec:
      volumes:
      - name: entrypoint
        configMap:
          name: {{ .Values.name }}-{{ .Values.name_suffix }}

      {{- if .Values.cluster_mode.schedule.enable }}
      nodeSelector:
        {{- with .Values.cluster_mode.schedule.dbInstancesNodeSelector }}
        {{- toYaml . | nindent 8}}
        {{- end }}
      {{- end }}

      containers:
      - name: {{ .Values.name }}-{{ .Values.name_suffix }}-read
        image: postgres:{{ .Values.version }}-alpine
        command: ["/bin/bash", "/entrypoint.d/replicas_entrypoint.sh"]
        imagePullPolicy: {{ .Values.imagePullPolicy }}

        ##__volumen_mount__##
        volumeMounts:
        {{- if .Values.storage.enable }}
        - name: {{ .Values.name }}-{{ .Values.name_suffix }}-read-data
          mountPath: /var/lib/postgresql/data
        {{- end }}
        - name: entrypoint
          mountPath: /entrypoint.d/replicas_entrypoint.sh
          subPath: replicas_entrypoint.sh

        #########__PORTS__############
        ports:
        - containerPort: 5432
          name: db-port

        {{- if .Values.resources.enable }}
        ##____RESOURCES____##
        resources:
          requests:
            cpu: {{ .Values.resources.dbInstances.requests.cpu }}
            memory: {{ .Values.resources.dbInstances.requests.memory }}
          limits:
            cpu: {{ .Values.resources.dbInstances.limits.cpu }}
            memory: {{ .Values.resources.dbInstances.limits.memory }}
        {{- end }}

        ##########__ENVS__############
        env:
        - name: PGDATA
          value: "/var/lib/postgresql/data/data"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}-{{ .Values.name_suffix }}
              key: root_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}-{{ .Values.name_suffix }}
              key: root_user_pwd
        - name: POSTGRES_REPLICATION_USER
          value: "cluster"
        - name: POSTGRES_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}-{{ .Values.name_suffix }}
              key: cluster_key
        - name: MASTER_HOST
          value: "{{ .Values.name }}-{{ .Values.name_suffix }}-master.{{ .Release.Namespace }}"
      
      {{- if .Values.metrics.enable }}
      #______________POSTGRES_EXPORTER___________________________________#
      - name: {{ .Values.name_suffix }}-exporter
        image: quay.io/prometheuscommunity/postgres-exporter:{{ .Values.metrics.exporterTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}

        ###_____PORTS______##
        ports:
        - containerPort: 9187
          name: metrics
        
        ##___ENVIRONMENT_VARIABLES___##
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef: 
              name: {{ .Values.name }}-{{ .Values.name_suffix }}
              key: exporter_source
      {{- end }}
        
  
  {{- if .Values.storage.enable }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.name }}-{{ .Values.name_suffix }}-read-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: {{ .Values.storage.storageClassName }} 
      resources:
        requests:
          storage: {{ .Values.storage.capacity }} 
  {{- end }}
{{- end }}