##_____________CLUSTER_SECRET_CONFIGURATIONS____________##
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-{{ .Values.name_suffix }}
type: Opaque
data:
  MINIO_ROOT_USER: {{ .Values.root_user | b64enc }}
  MINIO_ROOT_PASSWORD: {{ .Values.root_user_pwd | b64enc }}
  MINIO_SERVER_URL: {{ printf "http://%s-%s.%s:9000" .Values.name .Values.name_suffix .Release.Namespace | b64enc }}
  {{- if .Values.ingress.enable }}
  MINIO_BROWSER_REDIRECT_URL: {{ printf "http://%s" .Values.ingress.consoleHost | b64enc }}
  {{- else }}
  MINIO_BROWSER_REDIRECT_URL: {{ printf "http://%s-%s.%s:9090" .Values.name .Values.name_suffix .Release.Namespace | b64enc }}
  {{- end }}
