##_____________JOB_CONFIGURATIONS____________##
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-{{ .Values.name_suffix }}-job
type: Opaque
data:
  #_____________CLUSTER_CONFIG_JOB_ENTRYPOINT____________________________#
  config_job_entrypoint.sh: |
    {{- include (print $.Template.BasePath "/_cluster-config.sh.txt") . | b64enc | nindent 4 }}
