# Resources names prefix, all resources names will starts with <name>-<name_suffix>
name: test
name_suffix: mongodb

imagePullPolicy: IfNotPresent # all images pull policy
version: 6.0.4 # tag of mongodb official image

# CREDENTIALS
root_user: root
root_user_pwd: password

# DATABASES
databases:
- name: test_db # name of the database | for best practice use "_" to separe words 
  enable_backup: false # if true, enable backup and create cronjob
  # backup_suspend: false # if true, suspend backup cronjob
  backup_schedule: "0 2 * * 0" # used when enable_backup is true
  backup_s3_bucket_path: "test_db_backups" # used when enable_backup is true
  # admin_user: admin # database admin user | the user will be created if doesn't exist
  # admin_user_pwd: password # must be setted if admin_user is setted 

# RESOURCES LIMITS
resources: # mongodb instances resource limits
  enable: false
  wiredTigerCacheSizeGB: 1 # mongodb memory cache size | minimum 0.5
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 1500Mi

# CLUSTER MODE
cluster_mode:
  enable: false
  cluster_key: S0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t # cluster encription key
  readReplicas: 1 # minumum read replicas
  autoscaler: # you must enable resources limits to enable autoscaler
    enable: false
    targetCPUUtilizationPercentage: 80
    maxReadReplicas: 2
  schedule:
    enable: false
    #dbInstancesNodeSelector: # node selector for database instances
      #node_label: value


# STORAGE
storage:
  enable: false
  storageClassName: gp2
  capacity: 10Gi

# SERVICE
service:
  add_node_port: false # if true, exposes master instance on node port
  nodePort: 31950

# MONGO-EXPRESS
mongo_express: # enable this for tests only
  enable: false 

# BACKUPS
backups: # this will be used when one or more databases have enable_backup=true
  aws_access_key_id_base64: b2xh
  aws_secret_access_key_base64: b2xh
  aws_region: "eu-west-1"
  aws_s3_bucket_name: "backups-example"