apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {{- $access := printf "%s:%s" .Values.user .Values.password | b64enc }}
    {{- $url := printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" .Values.url $access }}
    {{- $url | b64enc | nindent 4 }}