{{- if .Values.job.envs -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: Opaque
data:
  {{- range $key, $value := .Values.job.envs }}
  {{ $key }}: |
    {{- $value | toString | b64enc | nindent 4 }}
  {{- end }}
{{- end }}

# DOTENV
{{- if .Values.job.dotenv }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-dotenv
type: Opaque
data:
  {{ .Values.job.dotenv.file }}: |
    {{- .Values.job.dotenv.content | toString | b64enc | nindent 4 }}
{{- end }}