apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}

spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
          imagePullPolicy: {{ .Values.deployment.pullPolicy }}

          {{- if .Values.deployment.ports }}
          ports:
          {{- range .Values.deployment.ports }}
          - containerPort: {{ .port }}
            name: {{ .name }}
          {{- end }}
          {{- end }}

          {{- $root := . }}

          {{- if .Values.deployment.envs }}
          env:
          {{- range .Values.deployment.envs }}
          - name: {{ .name }}
            valueFrom:
              configMapKeyRef:
                name: {{ $root.Values.name }}-configmap
                key: {{ .name }}
          {{- end }}
          {{- end }}

          {{- if .Values.deployment.secrets }}
          {{- if .Values.deployment.envs }}
          {{- else }}
          env:
          {{- end }}
          {{- range .Values.deployment.secrets }}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: {{ $root.Values.name }}-secret
                key: {{ .name }}
          {{- end }}
          {{- end }}