{{- if .Values.deployment.envs -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: Opaque
data:
  {{- range $key, $value := .Values.deployment.envs }}
  {{ $key }}: |
    {{- $value | toString | b64enc | nindent 4 }}
  {{- end }}
{{- end }}

# DOTENV
{{- if .Values.deployment.dotenv }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-dotenv
type: Opaque
data:
  {{ .Values.deployment.dotenv.file }}: |
    {{- .Values.deployment.dotenv.content | toString | b64enc | nindent 4 }}
{{- end }}