{{- if .Values.deployment.secrets -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
data:

  {{- range .Values.deployment.secrets }}
  {{ .name }}: {{ .value }}
  {{- end }}

{{- end }}