{{- if .Values.resources.enable }}
{{- if and .Values.cluster_mode.enable  .Values.cluster_mode.autoscaler.enable -}}
#____________________READ_REPLICAS_AUTOSCALER_____________________________________#
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}-{{ .Values.name_suffix }}-read
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Values.name }}-{{ .Values.name_suffix }}-read
  maxReplicas: {{ .Values.cluster_mode.autoscaler.maxReadReplicas }}
  minReplicas: {{ .Values.cluster_mode.readReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.cluster_mode.autoscaler.targetCPUUtilizationPercentage }}

{{- end }}
{{- end }}