##_____________CLUSTER_SECRET_CONFIGURATIONS____________##
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-{{ .Values.name_suffix }}
type: Opaque
data:
  root_user: {{ .Values.root_user | b64enc }}
  root_user_pwd: {{ .Values.root_user_pwd | b64enc }}
  aws_access_key_id: {{ .Values.backups.aws_access_key_id_base64 }}
  aws_secret_access_key: {{ .Values.backups.aws_secret_access_key_base64 }}
  
  {{- if .Values.cluster_mode.enable }}
  cluster_key: |
    {{- .Values.cluster_mode.cluster_key | b64enc | nindent 4}}
  {{- end }}

  #_____________CLUSTER_CONFIG_JOB_ENTRYPOINT____________________________#
  config_job_entrypoint.sh: |
    {{- include (print $.Template.BasePath "/_cluster-config.sh.txt") . | b64enc | nindent 4 }}
  
  #_____________CLUSTER_USERS_XML____________________________#
  users.xml: |
    {{- include (print $.Template.BasePath "/_users.xml.txt") . | b64enc | nindent 4 }}
  
  config.xml: |
    {{- include (print $.Template.BasePath "/_config.xml.txt") . | b64enc | nindent 4 }}
