apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-{{ .Values.name_suffix }}
data:

  #_____________BACKUP_JOB_ENTRYPOINT________________________________________#
  backup_job_entrypoint.sh: |
    mkdir -p /data/backups
    export today=$(date '+%Y-%m-%d-%H_%M_%S')
    
    echo "LOG: Make the backup ${today}"
    mysqldump -h ${MASTER_HOST} -u ${MYSQL_ROOT_USER} -p${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} > /data/backups/${today}.sql
    if (( $? != 0 )); then exit 1; fi

    echo "LOG: Compress the backup"
    cd /data/backups && tar czf ${today}.tar.gz ${today}.sql

    echo "LOG: Send backup ${today} to S3 bucket"
    python3 /code/upload_file.py /data/backups/${today}.tar.gz
  
  {{ if .Values.cluster_mode.enable }}
  #_____________MASTER_NODE_ENTRYPOINT_______________________________________#
  master_entrypoint.sh: |
    echo "LOG: CREATING REPLICATION USER"
    echo "
    CREATE USER '${MYSQL_REPLICATION_USER}'@'%' IDENTIFIED WITH mysql_native_password BY '${MYSQL_REPLICATION_PASSWORD}'; 
    GRANT REPLICATION SLAVE ON *.* TO '${MYSQL_REPLICATION_USER}'@'%';
    FLUSH PRIVILEGES;
    " > /var/lib/mysql/data.sql

    mysql -u ${MYSQL_ROOT_USER} -p${MYSQL_ROOT_PASSWORD} -f < /var/lib/mysql/data.sql
    rm /var/lib/mysql/data.sql
  
  #______________MASTER_NODE_CONFIGURATION____________________________________#
  master.conf.cnf: |
    [mysqld]
    max_connections = {{ .Values.max_connections }}
    server-id = 1
    log-bin = bin_log
    # GDIT
    gtid_mode=ON
    enforce-gtid-consistency=ON

    {{ $version := .Values.version | toString }}
    {{- if eq $version "5.7" }}
    datadir=/var/lib/mysql/data/
    {{- end }}



  #_____________READ_REPLICA_NODE_ENTRYPOINT____________________________#
  replicas_entrypoint.sh: |
    echo "LOG: Changing server id"
    echo "
    CHANGE REPLICATION SOURCE TO
    SOURCE_HOST = '${MASTER_HOST}', 
    SOURCE_USER = '${MYSQL_REPLICATION_USER}',
    SOURCE_PASSWORD = '${MYSQL_REPLICATION_PASSWORD}',
    SOURCE_AUTO_POSITION=1;
    START REPLICA;
    SET @@GLOBAL.read_only = ON;
    " > /var/lib/mysql/data.sql

    mysql -u ${MYSQL_ROOT_USER} -p${MYSQL_ROOT_PASSWORD} -f < /var/lib/mysql/data.sql
    rm /var/lib/mysql/data.sql


  #______________READ_REPLICA_NODE_CONFIGURATION_____________________________#
  read.conf.cnf: |
    [mysqld]
    max_connections = {{ .Values.max_connections }}
    server-id = 2
    log-bin = bin_log
    # GDIT
    read_only = ON
    relay-log = relay_bin_log
    gtid_mode=ON
    enforce-gtid-consistency=ON
    log-replica-updates=ON
    
    {{ $version := .Values.version | toString }}
    {{- if eq $version "5.7" }}
    datadir=/var/lib/mysql/data/
    {{- end }}
  {{- end }}