##______________________MASTER_NODE_DEPLOYMENT________________________________##
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-{{ .Values.name_suffix }}-master
  labels:
    app: {{ .Values.name }}-{{ .Values.name_suffix }}
    type: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-{{ .Values.name_suffix }}
      type: master
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-{{ .Values.name_suffix }}
        type: master
      annotations:
        {{- $config_map := include (print $.Template.BasePath "/configmap.yaml") . }}
        {{- $secret := printf "%s%s%s" .Values.root_user .Values.root_user_pwd .Values.cluster_mode.cluster_key }}
        checksum/config: {{ printf "%s%s" $config_map $secret | sha256sum }}
    spec:
      {{- if or .Values.storage.enable .Values.cluster_mode.enable }}
      volumes:
      {{- end }}
      {{- if .Values.storage.enable }}
        - name: {{ .Values.name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-{{ .Values.name_suffix }}-master-data-pvc
      {{- end }}
      {{- if .Values.cluster_mode.enable }}
        - name: entrypoint
          configMap:
            name: {{ .Values.name }}-{{ .Values.name_suffix }}
        - name: config
          configMap:
            name: {{ .Values.name }}-{{ .Values.name_suffix }}
      {{- end }}
      
      {{- if and .Values.cluster_mode.enable .Values.cluster_mode.schedule.enable }}
      nodeSelector:
        {{- with .Values.cluster_mode.schedule.dbInstancesNodeSelector }}
        {{- toYaml . | nindent 8}}
        {{- end }}
      {{- end }}

      containers:
        - name: {{ .Values.name }}-{{ .Values.name_suffix }}-master
          image: mysql:{{ .Values.version }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          
          {{- if or .Values.storage.enable .Values.cluster_mode.enable }}
          ##__volumen_mount__##
          volumeMounts:
          {{- end }}
          {{- if .Values.storage.enable }}
          - name: {{ .Values.name }}-data
            mountPath: /var/lib/mysql
          {{- end }}
          {{- if .Values.cluster_mode.enable }}
          - name: entrypoint
            mountPath: /docker-entrypoint-initdb.d/master_entrypoint.sh
            subPath: master_entrypoint.sh
          - name: config
            mountPath: /etc/mysql/conf.d/master.conf.cnf
            subPath: master.conf.cnf
          {{- end }}

          ###_____PORTS______##
          ports:
          - containerPort: 3306
            name: db-port
          
          {{- if .Values.resources.enable }}
          ##____RESOURCES____##
          resources:
            requests:
              cpu: {{ .Values.resources.dbInstances.requests.cpu }}
              memory: {{ .Values.resources.dbInstances.requests.memory }}
            limits:
              cpu: {{ .Values.resources.dbInstances.limits.cpu }}
              memory: {{ .Values.resources.dbInstances.limits.memory }}
          {{- end }}
          
          ##___ENVIRONMENT_VARIABLES___##
          env:
          - name: MYSQL_ROOT_USER
            valueFrom:
              secretKeyRef: 
                name: {{ .Values.name }}-{{ .Values.name_suffix }}
                key: root_user
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: {{ .Values.name }}-{{ .Values.name_suffix }}
                key: root_user_pwd
          {{- if .Values.cluster_mode.enable }}
          - name: MYSQL_REPLICATION_USER
            value: "cluster"
          - name: MYSQL_REPLICATION_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: {{ .Values.name }}-{{ .Values.name_suffix }}
                key: cluster_key
          {{- end }}


{{- if .Values.cluster_mode.enable }}
---
##_____________________________________PROXYSQL_DEPLOYMENT________________________________##
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-{{ .Values.name_suffix }}-proxy
spec:
  replicas: {{ .Values.cluster_mode.proxysqlReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-{{ .Values.name_suffix }}
      type: proxysql
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-{{ .Values.name_suffix }}
        type: proxysql
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: proxysql-config
          secret:
            secretName: {{ .Values.name }}-{{ .Values.name_suffix }}
      
      {{- if .Values.cluster_mode.schedule.enable }}
      nodeSelector:
        {{- with .Values.cluster_mode.schedule.proxysqlNodeSelector }}
        {{- toYaml . | nindent 8}}
        {{- end }}
      {{- end }}

      containers:
        - name: {{ .Values.name }}-{{ .Values.name_suffix }}-proxysql
          image: proxysql/proxysql:{{ .Values.cluster_mode.proxysqlTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          
          ports:
          - containerPort: 3306
            name: proxysql
          
          volumeMounts:
          - name: proxysql-config
            mountPath: /etc/proxysql.cnf
            subPath: proxysql.cnf
          
          {{- if .Values.resources.enable }}
          ##____RESOURCES____##
          resources:
            requests:
              cpu: {{ .Values.resources.proxysql.requests.cpu }}
              memory: {{ .Values.resources.proxysql.requests.memory }}
            limits:
              cpu: {{ .Values.resources.proxysql.limits.cpu }}
              memory: {{ .Values.resources.proxysql.limits.memory }}
          {{- end }}

{{- end }}