apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-{{ .Values.name_suffix }}
type: Opaque
data:
  root_user: {{ .Values.root_user | b64enc }}
  root_user_pwd: {{ .Values.root_user_pwd | b64enc }}
  aws_access_key_id: {{ .Values.backups.aws_access_key_id_base64 }}
  aws_secret_access_key: {{ .Values.backups.aws_secret_access_key_base64 }}
  
  {{- if .Values.metrics.enable }}
  #_______________EXPORTER_CONF______________________________________#
  exporter_source: {{ printf "%s:%s@(localhost:3306)/" .Values.root_user .Values.root_user_pwd | b64enc }}
  {{- end }}

  {{- if .Values.cluster_mode.enable }}
  #_________________SOME_CLUSTER_CONF___________________________________________#
  cluster_key: |
    {{- .Values.cluster_mode.cluster_key | b64enc | nindent 4}}
  
  #_________________PROXYSQL_CONFIGURATION________________________________________#
  proxysql.cnf: |
    {{- include (print $.Template.BasePath "/_proxysql.cnf.txt") . | b64enc | nindent 4 }}
  
  {{- end }}

  #__________________________CONFIG_JOB_ENTRYPOINT____________________________________#
  config_job_entrypoint.sh: |
    {{- include (print $.Template.BasePath "/_cluster-config.sh.txt") . | b64enc | nindent 4 }}
