##_____________CLUSTER_SECRET_CONFIGURATIONS____________##
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-{{ .Values.name_suffix }}
type: Opaque
data:
  root_user: {{ .Values.root_user | b64enc }}
  root_user_pwd: {{ .Values.root_user_pwd | b64enc }}
  aws_access_key_id: {{ .Values.backups.aws_access_key_id_base64 }}
  aws_secret_access_key: {{ .Values.backups.aws_secret_access_key_base64 }}
  
  {{- if .Values.cluster_mode.enable }}
  cluster_key: |
    {{- .Values.cluster_mode.cluster_key | b64enc | nindent 4}}
  {{- end }}

  {{- if .Values.mongo_express.enable }}
  # url configuration
  {{- $url := printf "mongodb://%s:%s@%s-%s-master:27017" .Values.root_user .Values.root_user_pwd .Values.name .Values.name_suffix }}
  
  {{- if .Values.cluster_mode.enable }}
  {{- $url := printf "%s,%s-%s-read:27017/?replicaSet=%s&readPreference=secondaryPreferred&" $url .Values.name .Values.name_suffix .Values.name }}
  {{ .Values.name_suffix }}_url: {{ printf "%sauthSource=admin" $url | b64enc }}
  
  {{- else }}
  {{- $url := printf "%s/?" $url}}
  {{ .Values.name_suffix }}_url: {{ printf "%sauthSource=admin" $url | b64enc }}
  {{- end }}

  {{- end }}

  #_____________CLUSTER_CONFIG_JOB_ENTRYPOINT____________________________#
  config_job_entrypoint.sh: |
    {{- include (print $.Template.BasePath "/_cluster-config.sh.txt") . | b64enc | nindent 4 }}
