{{- if .Values.cluster_mode.enable }}
#_________________________READ_REPLICAS_STATEFULSET________________________#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}-{{ .Values.name_suffix }}-read
  labels:
    app: {{ .Values.name }}-{{ .Values.name_suffix }}
    type: read
spec:
  replicas: {{ .Values.cluster_mode.readReplicas }}
  serviceName: "{{ .Values.name }}-{{ .Values.name_suffix }}-read"
  selector:
    matchLabels:
      app: {{ .Values.name }}-{{ .Values.name_suffix }}
      type: read
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-{{ .Values.name_suffix }}
        type: read
      annotations:
        {{- $config_map := include (print $.Template.BasePath "/configmap.yaml") . }}
        {{- $secret := printf "%s%s%s" .Values.root_user .Values.root_user_pwd .Values.cluster_mode.cluster_key }}
        checksum/config: {{ printf "%s%s" $config_map $secret | sha256sum }}
    spec:
      volumes:
      - name: entrypoint
        configMap:
          name: {{ .Values.name }}-{{ .Values.name_suffix }}
      
      {{- if .Values.cluster_mode.schedule.enable }}
      nodeSelector:
        {{- with .Values.cluster_mode.schedule.dbInstancesNodeSelector }}
        {{- toYaml . | nindent 8}}
        {{- end }}
      {{- end }}

      containers:
      - name: {{ .Values.name }}-{{ .Values.name_suffix }}-read
        image: mongo:{{ .Values.version }}
        command: ["/bin/bash", "/entrypoint.d/replicas_entrypoint.sh"]
        imagePullPolicy: {{ .Values.imagePullPolicy }}

        ##__volumen_mount__##
        volumeMounts:
        {{- if .Values.storage.enable }}
        - name: {{ .Values.name }}-{{ .Values.name_suffix }}-read-data
          mountPath: /data/db
        {{- end }}
        - name: entrypoint
          mountPath: /entrypoint.d/replicas_entrypoint.sh
          subPath: replicas_entrypoint.sh

        #########__PORTS__############
        ports:
        - containerPort: 27017
          name: db-port

        {{- if .Values.resources.enable }}
        ##____RESOURCES____##
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        {{- end }}

        ##########__ENVS__############
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}-{{ .Values.name_suffix }}
              key: root_user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}-{{ .Values.name_suffix }}
              key: root_user_pwd
        - name: MONGO_CACHE_SIZE_GB
          value: "{{ .Values.resources.wiredTigerCacheSizeGB }}"
        - name: MONGO_CLUSTER_REPLICASET
          value: "{{ .Values.name }}"
        - name: MONGO_MASTER_HOST
          value: "{{ .Values.name }}-{{ .Values.name_suffix }}-master.{{ .Release.Namespace }}"
        - name: MONGO_CLUSTER_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}-{{ .Values.name_suffix }}
              key: cluster_key
  
  {{- if .Values.storage.enable }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.name }}-{{ .Values.name_suffix }}-read-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: {{ .Values.storage.storageClassName }} 
      resources:
        requests:
          storage: {{ .Values.storage.capacity }} 
  {{- end }}
{{- end }}