{{- $root := . }}
{{- if .Values.cronjob.volumes }}
{{- range .Values.cronjob.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $root.Values.name }}-{{ .name }}-pvc
spec:
  storageClassName: {{ .storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .capacity }}
{{- end }}
{{- end }}